name: CI/CD

on: [push, pull_request]

jobs:

  package:
    name: Maven Package (no tests) 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
        
  test:
    name: Coverage tests
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and test with Maven
      run: mvn clean test

    - name: Display coverage
      run: |
        cat target/site/jacoco/index.html | grep -oP '(?<=<td class="ctr2">)[^<]+' | head -n 1
